version: "2.2"
services:
  jobmanager:
    image: flink:latest
    ports:
      - "8082:8082"
    command: standalone-job --job-classname com.job.ClassName 
    volumes:
      - flink-data:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 2        

  taskmanager:
    image: flink:latest
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    volumes:
      - flink-data:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 2
volumes:
  flink-data: